/* This file is part of natlab.
 * https://github.com/mvasilkov/natlab
 * MIT+Ethics License | Copyright (c) 2022 Mark Vasilkov
 * See https://github.com/mvasilkov/natlab/blob/master/LICENSE
 */
'use strict'

export const keyboardEventCodes = [
  '',
  'Again',
  /* Microsoft_Brave */ 'AltLeft',
  /* Microsoft_Brave */ 'AltRight',
  /* Microsoft_Brave */ 'ArrowDown',
  /* Microsoft_Brave */ 'ArrowLeft',
  /* Microsoft_Brave */ 'ArrowRight',
  /* Microsoft_Brave */ 'ArrowUp',
  'AudioVolumeDown',
  'AudioVolumeMute',
  'AudioVolumeUp',
  /* Microsoft_Brave */ 'Backquote',
  /* Microsoft_Brave */ 'Backslash',
  /* Microsoft_Brave */ 'Backspace',
  /* Microsoft_Brave */ 'BracketLeft',
  /* Microsoft_Brave */ 'BracketRight',
  'BrowserBack',
  'BrowserFavorites',
  'BrowserForward',
  'BrowserHome',
  'BrowserRefresh',
  'BrowserSearch',
  'BrowserStop',
  /* Microsoft_Brave */ 'CapsLock',
  /* Microsoft_Brave */ 'Comma',
  /* Microsoft_Brave */ 'ContextMenu',
  /* Microsoft_Brave */ 'ControlLeft',
  /* Microsoft_Brave */ 'ControlRight',
  'Convert',
  'Copy',
  'Cut',
  /* Microsoft_Brave */ 'Delete',
  /* Microsoft_Brave */ 'Digit0',
  /* Microsoft_Brave */ 'Digit1',
  /* Microsoft_Brave */ 'Digit2',
  /* Microsoft_Brave */ 'Digit3',
  /* Microsoft_Brave */ 'Digit4',
  /* Microsoft_Brave */ 'Digit5',
  /* Microsoft_Brave */ 'Digit6',
  /* Microsoft_Brave */ 'Digit7',
  /* Microsoft_Brave */ 'Digit8',
  /* Microsoft_Brave */ 'Digit9',
  'Eject',
  /* Microsoft_Brave */ 'End',
  /* Microsoft_Brave */ 'Enter',
  /* Microsoft_Brave */ 'Equal',
  /* Microsoft_Brave */ 'Escape',
  /* Microsoft_Brave */ 'F1',
  /* Microsoft_Brave */ 'F2',
  /* Microsoft_Brave */ 'F3',
  /* Microsoft_Brave */ 'F4',
  /* Microsoft_Brave */ 'F5',
  /* Microsoft_Brave */ 'F6',
  /* Microsoft_Brave */ 'F7',
  /* Microsoft_Brave */ 'F8',
  /* Microsoft_Brave */ 'F9',
  /* Microsoft_Brave */ 'F10',
  /* Microsoft_Brave */ 'F11',
  /* Microsoft_Brave */ 'F12',
  'F13',
  'F14',
  'F15',
  'F16',
  'F17',
  'F18',
  'F19',
  'F20',
  'F21',
  'F22',
  'F23',
  'F24',
  'Find',
  'Fn',
  'Help',
  /* Microsoft_Brave */ 'Home',
  /* Microsoft_Brave */ 'Insert',
  'IntlBackslash',
  'IntlRo',
  'IntlYen',
  'KanaMode',
  /* Microsoft_Brave */ 'KeyA',
  /* Microsoft_Brave */ 'KeyB',
  /* Microsoft_Brave */ 'KeyC',
  /* Microsoft_Brave */ 'KeyD',
  /* Microsoft_Brave */ 'KeyE',
  /* Microsoft_Brave */ 'KeyF',
  /* Microsoft_Brave */ 'KeyG',
  /* Microsoft_Brave */ 'KeyH',
  /* Microsoft_Brave */ 'KeyI',
  /* Microsoft_Brave */ 'KeyJ',
  /* Microsoft_Brave */ 'KeyK',
  /* Microsoft_Brave */ 'KeyL',
  /* Microsoft_Brave */ 'KeyM',
  /* Microsoft_Brave */ 'KeyN',
  /* Microsoft_Brave */ 'KeyO',
  /* Microsoft_Brave */ 'KeyP',
  /* Microsoft_Brave */ 'KeyQ',
  /* Microsoft_Brave */ 'KeyR',
  /* Microsoft_Brave */ 'KeyS',
  /* Microsoft_Brave */ 'KeyT',
  /* Microsoft_Brave */ 'KeyU',
  /* Microsoft_Brave */ 'KeyV',
  /* Microsoft_Brave */ 'KeyW',
  /* Microsoft_Brave */ 'KeyX',
  /* Microsoft_Brave */ 'KeyY',
  /* Microsoft_Brave */ 'KeyZ',
  'Lang1',
  'Lang2',
  'Lang3',
  'Lang4',
  'Lang5',
  'LaunchApp1',
  'LaunchApp2',
  'LaunchMail',
  'MediaPlayPause',
  'MediaSelect',
  'MediaStop',
  'MediaTrackNext',
  'MediaTrackPrevious',
  /* Microsoft_Brave */ 'MetaLeft',
  'MetaRight',
  /* Microsoft_Brave */ 'Minus',
  'NonConvert',
  /* Microsoft_Brave */ 'NumLock',
  /* Microsoft_Brave */ 'Numpad0',
  /* Microsoft_Brave */ 'Numpad1',
  /* Microsoft_Brave */ 'Numpad2',
  /* Microsoft_Brave */ 'Numpad3',
  /* Microsoft_Brave */ 'Numpad4',
  /* Microsoft_Brave */ 'Numpad5',
  /* Microsoft_Brave */ 'Numpad6',
  /* Microsoft_Brave */ 'Numpad7',
  /* Microsoft_Brave */ 'Numpad8',
  /* Microsoft_Brave */ 'Numpad9',
  /* Microsoft_Brave */ 'NumpadAdd',
  'NumpadComma',
  /* Microsoft_Brave */ 'NumpadDecimal',
  /* Microsoft_Brave */ 'NumpadDivide',
  /* Microsoft_Brave */ 'NumpadEnter',
  'NumpadEqual',
  /* Microsoft_Brave */ 'NumpadMultiply',
  'NumpadParenLeft',
  'NumpadParenRight',
  /* Microsoft_Brave */ 'NumpadSubtract',
  'OSLeft',
  'OSRight',
  'Open',
  /* Microsoft_Brave */ 'PageDown',
  /* Microsoft_Brave */ 'PageUp',
  'Paste',
  /* Microsoft_Brave */ 'Pause',
  /* Microsoft_Brave */ 'Period',
  'Power',
  /* Microsoft_Brave */ 'PrintScreen',
  'Props',
  /* Microsoft_Brave */ 'Quote',
  /* Microsoft_Brave */ 'ScrollLock',
  'Select',
  /* Microsoft_Brave */ 'Semicolon',
  /* Microsoft_Brave */ 'ShiftLeft',
  /* Microsoft_Brave */ 'ShiftRight',
  /* Microsoft_Brave */ 'Slash',
  'Sleep',
  /* Microsoft_Brave */ 'Space',
  /* Microsoft_Brave */ 'Tab',
  'Undo',
  'Unidentified',
  'VolumeDown',
  'VolumeMute',
  'VolumeUp',
  'WakeUp',
]
